apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: maven-sample
  name: maven-sample
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: maven-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maven-sample
    spec:
      containers:
      - image: {{ .Values.image }}
        name: maven-sample
        resources: {}
status: {}
