apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: maven-sample
    app.kubernetes.io/managed-by: Helm
  name: maven-sample
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: maven-sample
status:
  loadBalancer: {}
