apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm-maven
  name: helm-maven
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-maven
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm-maven
    spec:
      containers:
      - image: {{ .Values.image }}
        name: helm-maven
        ports:
        - containerPort: 9000
          name: "http"
        - containerPort: 5005
          name: "debug"
        resources: {}
status: {}
